# Generated by Django 5.2.7 on 2026-04-05 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAdmin',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('txt_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('Account_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Account_type', models.CharField(max_length=30)),
                ('amt', models.FloatField(default=0)),
                ('pin', models.IntegerField()),
                ('strt_date', models.DateField(blank=True, null=True)),
                ('txt_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('txt_no', models.IntegerField(primary_key=True, serialize=False)),
                ('txt_type', models.CharField(max_length=30)),
                ('txt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Account_no', models.ForeignKey(db_column='Account_no', on_delete=django.db.models.deletion.CASCADE, to='main.bankuser')),
            ],
        ),
    ]
